"""Public compatibility surface for :mod:`gnx_py.ionosphere`.

The ionosphere package historically re-exported broad ``import *`` surfaces
from its implementation modules.  ``__all__`` intentionally snapshots that
wide surface for backward compatibility; future cleanup can prune accidental
symbols only after a deprecation/migration step.

Active user-facing API includes ``TECConfig``, ``TECSession``, ``STECMonitor``,
GIM/IONEX helpers, ionosphere model helpers, monitoring functions and kriging
utilities.  Several names below are legacy or accidental exports retained so
``from gnx_py.ionosphere import *`` remains compatible.
"""

from .config import *
from .models import *
from .utils import *
from .monitoring import *
from .smg import *
from .kriging import *

__all__ = [
    "Any",
    "ArrayLike",
    "BroadcastInterp",
    "C",
    "CSDetector",
    "Calibration",
    "Callable",
    "CoordFrame",
    "CustomWrapper",
    "DDOF_POP",
    "DDPreprocessing",
    "DMAX_KM",
    "DMIN_KM",
    "DPI",
    "Dict",
    "EARTH_RADIUS_KM",
    "ExponentialVariogram",
    "FIGSIZE",
    "Final",
    "GNSSDataProcessor2",
    "GaussianVariogram",
    "GenericVariogram",
    "IGRFDipole",
    "IONO_H",
    "IONO_SHELL_H_KM",
    "ITRS",
    "IonoKrigingMonitor",
    "Iterable",
    "KrigingMode",
    "List",
    "Literal",
    "MAX_GAP_S",
    "MAX_PAIR_PER_EPOCH",
    "MIN_ELEV_DEG",
    "MatplotlibDeprecationWarning",
    "Optional",
    "OrbitData",
    "OrdinaryKrigingGeo",
    "PI",
    "Path",
    "Protocol",
    "ROTI_MIN_SAMPLES",
    "ROTI_WINDOW_MIN",
    "Re",
    "Region",
    "SIGNALS",
    "SPLIT_BY_DAY",
    "STECMonitor",
    "Sequence",
    "Set",
    "SolarGeomagneticTransformer",
    "SparksVariogram",
    "SphericalVariogram",
    "TECConfig",
    "TECSession",
    "Time",
    "Tuple",
    "Union",
    "UniversalKrigingGeo",
    "VariogramLike",
    "annotations",
    "apply_cheby_lowpass_1d",
    "apply_savgol_filter_1d",
    "apply_stec_bias_policy",
    "bias_policy",
    "build_G",
    "cKDTree",
    "cheby1",
    "cho_factor",
    "cho_solve",
    "compute_gix",
    "compute_ntcm_grid",
    "compute_roti_global_scale",
    "compute_roti_links",
    "compute_sid",
    "config",
    "dataclass",
    "datetime",
    "datetime2doy",
    "datetime2toc",
    "distance",
    "ecef2geodetic",
    "ecef_distance_km",
    "emission_interp",
    "enu_basis_at",
    "field",
    "filtfilt",
    "frequency_hz",
    "geographic2geomagnetic_latitude",
    "get_ipp",
    "get_local_time",
    "get_sun",
    "get_vtec",
    "gpst2utc",
    "great_circle_distance_km",
    "gridspec",
    "guarded_session_run",
    "initial_bearing_deg",
    "ionex",
    "klobuchar",
    "klobuchar_delay",
    "kriging",
    "lagrange_emission_interp",
    "lagrange_reception_interp",
    "llh_to_ecef",
    "load_stec_folder",
    "local2gsow",
    "logger",
    "logging",
    "make_ionofree",
    "make_roti_snapshots",
    "mapping_M",
    "math",
    "mdates",
    "mode_layout",
    "mode_signals",
    "models",
    "monitoring",
    "mpatches",
    "mpl",
    "njit",
    "np",
    "ntcm_vtec",
    "os",
    "pd",
    "plot_gix",
    "plot_gix_family",
    "plot_roti_snapshot",
    "plt",
    "read_sp3",
    "roti_snapshot_grid",
    "run_NTCM_for_gps",
    "runtime_checkable",
    "save_grids_to_netcdf",
    "savgol_filter",
    "smg",
    "sol_zen_deps",
    "spherical2ecef",
    "spherical_midpoint",
    "stec_mf",
    "sun_dec",
    "u",
    "utils",
    "waas_kriging_point_fast",
    "warnings",
    "xr",
]
